#pragma line 1 "./targeted_functions/gcd/targeted_function.c" ::: 0
#pragma line 1 "./targeted_functions/gcd/targeted_function.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 147 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "E:/Xilinx_install_dir/15.4/Vivado_HLS/2015.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 11
#pragma line 283 "E:/Xilinx_install_dir/15.4/Vivado_HLS/2015.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 64
#pragma line 7 "<command line>" 2 ::: 191
#pragma line 1 "<built-in>" 2 ::: 192
#pragma line 1 "./targeted_functions/gcd/targeted_function.c" 2 ::: 193
