// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xtargeted_function.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XTargeted_function_CfgInitialize(XTargeted_function *InstancePtr, XTargeted_function_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Rm_BaseAddress = ConfigPtr->Rm_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XTargeted_function_Start(XTargeted_function *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTargeted_function_ReadReg(InstancePtr->Rm_BaseAddress, XTARGETED_FUNCTION_RM_ADDR_AP_CTRL) & 0x80;
    XTargeted_function_WriteReg(InstancePtr->Rm_BaseAddress, XTARGETED_FUNCTION_RM_ADDR_AP_CTRL, Data | 0x01);
}

u32 XTargeted_function_IsDone(XTargeted_function *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTargeted_function_ReadReg(InstancePtr->Rm_BaseAddress, XTARGETED_FUNCTION_RM_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XTargeted_function_IsIdle(XTargeted_function *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTargeted_function_ReadReg(InstancePtr->Rm_BaseAddress, XTARGETED_FUNCTION_RM_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XTargeted_function_IsReady(XTargeted_function *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTargeted_function_ReadReg(InstancePtr->Rm_BaseAddress, XTARGETED_FUNCTION_RM_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XTargeted_function_EnableAutoRestart(XTargeted_function *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTargeted_function_WriteReg(InstancePtr->Rm_BaseAddress, XTARGETED_FUNCTION_RM_ADDR_AP_CTRL, 0x80);
}

void XTargeted_function_DisableAutoRestart(XTargeted_function *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTargeted_function_WriteReg(InstancePtr->Rm_BaseAddress, XTARGETED_FUNCTION_RM_ADDR_AP_CTRL, 0);
}

u32 XTargeted_function_Get_return(XTargeted_function *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTargeted_function_ReadReg(InstancePtr->Rm_BaseAddress, XTARGETED_FUNCTION_RM_ADDR_AP_RETURN);
    return Data;
}
void XTargeted_function_Set_input_000(XTargeted_function *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTargeted_function_WriteReg(InstancePtr->Rm_BaseAddress, XTARGETED_FUNCTION_RM_ADDR_INPUT_000_DATA, Data);
}

u32 XTargeted_function_Get_input_000(XTargeted_function *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTargeted_function_ReadReg(InstancePtr->Rm_BaseAddress, XTARGETED_FUNCTION_RM_ADDR_INPUT_000_DATA);
    return Data;
}

void XTargeted_function_Set_input_001(XTargeted_function *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTargeted_function_WriteReg(InstancePtr->Rm_BaseAddress, XTARGETED_FUNCTION_RM_ADDR_INPUT_001_DATA, Data);
}

u32 XTargeted_function_Get_input_001(XTargeted_function *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTargeted_function_ReadReg(InstancePtr->Rm_BaseAddress, XTARGETED_FUNCTION_RM_ADDR_INPUT_001_DATA);
    return Data;
}

u32 XTargeted_function_Get_output_000(XTargeted_function *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTargeted_function_ReadReg(InstancePtr->Rm_BaseAddress, XTARGETED_FUNCTION_RM_ADDR_OUTPUT_000_DATA);
    return Data;
}

u32 XTargeted_function_Get_output_000_vld(XTargeted_function *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTargeted_function_ReadReg(InstancePtr->Rm_BaseAddress, XTARGETED_FUNCTION_RM_ADDR_OUTPUT_000_CTRL);
    return Data & 0x1;
}

void XTargeted_function_InterruptGlobalEnable(XTargeted_function *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTargeted_function_WriteReg(InstancePtr->Rm_BaseAddress, XTARGETED_FUNCTION_RM_ADDR_GIE, 1);
}

void XTargeted_function_InterruptGlobalDisable(XTargeted_function *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTargeted_function_WriteReg(InstancePtr->Rm_BaseAddress, XTARGETED_FUNCTION_RM_ADDR_GIE, 0);
}

void XTargeted_function_InterruptEnable(XTargeted_function *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XTargeted_function_ReadReg(InstancePtr->Rm_BaseAddress, XTARGETED_FUNCTION_RM_ADDR_IER);
    XTargeted_function_WriteReg(InstancePtr->Rm_BaseAddress, XTARGETED_FUNCTION_RM_ADDR_IER, Register | Mask);
}

void XTargeted_function_InterruptDisable(XTargeted_function *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XTargeted_function_ReadReg(InstancePtr->Rm_BaseAddress, XTARGETED_FUNCTION_RM_ADDR_IER);
    XTargeted_function_WriteReg(InstancePtr->Rm_BaseAddress, XTARGETED_FUNCTION_RM_ADDR_IER, Register & (~Mask));
}

void XTargeted_function_InterruptClear(XTargeted_function *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTargeted_function_WriteReg(InstancePtr->Rm_BaseAddress, XTARGETED_FUNCTION_RM_ADDR_ISR, Mask);
}

u32 XTargeted_function_InterruptGetEnabled(XTargeted_function *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XTargeted_function_ReadReg(InstancePtr->Rm_BaseAddress, XTARGETED_FUNCTION_RM_ADDR_IER);
}

u32 XTargeted_function_InterruptGetStatus(XTargeted_function *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XTargeted_function_ReadReg(InstancePtr->Rm_BaseAddress, XTARGETED_FUNCTION_RM_ADDR_ISR);
}

