// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="targeted_function,hls_ip_2015_4,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.080000,HLS_SYN_LAT=5,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=4,HLS_SYN_FF=188,HLS_SYN_LUT=297}" *)

module targeted_function (
        ap_clk,
        ap_rst_n,
        s_axi_rm_AWVALID,
        s_axi_rm_AWREADY,
        s_axi_rm_AWADDR,
        s_axi_rm_WVALID,
        s_axi_rm_WREADY,
        s_axi_rm_WDATA,
        s_axi_rm_WSTRB,
        s_axi_rm_ARVALID,
        s_axi_rm_ARREADY,
        s_axi_rm_ARADDR,
        s_axi_rm_RVALID,
        s_axi_rm_RREADY,
        s_axi_rm_RDATA,
        s_axi_rm_RRESP,
        s_axi_rm_BVALID,
        s_axi_rm_BREADY,
        s_axi_rm_BRESP,
        interrupt
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 6'b1;
parameter    ap_ST_st2_fsm_1 = 6'b10;
parameter    ap_ST_st3_fsm_2 = 6'b100;
parameter    ap_ST_st4_fsm_3 = 6'b1000;
parameter    ap_ST_st5_fsm_4 = 6'b10000;
parameter    ap_ST_st6_fsm_5 = 6'b100000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    C_S_AXI_RM_DATA_WIDTH = 32;
parameter    ap_const_int64_8 = 8;
parameter    C_S_AXI_RM_ADDR_WIDTH = 12;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_true = 1'b1;
parameter    C_S_AXI_RM_WSTRB_WIDTH = (C_S_AXI_RM_DATA_WIDTH / ap_const_int64_8);
parameter    C_S_AXI_WSTRB_WIDTH = (C_S_AXI_DATA_WIDTH / ap_const_int64_8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_rm_AWVALID;
output   s_axi_rm_AWREADY;
input  [C_S_AXI_RM_ADDR_WIDTH - 1 : 0] s_axi_rm_AWADDR;
input   s_axi_rm_WVALID;
output   s_axi_rm_WREADY;
input  [C_S_AXI_RM_DATA_WIDTH - 1 : 0] s_axi_rm_WDATA;
input  [C_S_AXI_RM_WSTRB_WIDTH - 1 : 0] s_axi_rm_WSTRB;
input   s_axi_rm_ARVALID;
output   s_axi_rm_ARREADY;
input  [C_S_AXI_RM_ADDR_WIDTH - 1 : 0] s_axi_rm_ARADDR;
output   s_axi_rm_RVALID;
input   s_axi_rm_RREADY;
output  [C_S_AXI_RM_DATA_WIDTH - 1 : 0] s_axi_rm_RDATA;
output  [1:0] s_axi_rm_RRESP;
output   s_axi_rm_BVALID;
input   s_axi_rm_BREADY;
output  [1:0] s_axi_rm_BRESP;
output   interrupt;

reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm = 6'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_24;
reg    ap_ready;
wire  signed [31:0] input_000;
wire  signed [31:0] input_001;
wire   [31:0] output_000;
reg    output_000_ap_vld;
wire   [31:0] ap_return;
wire    targeted_function_rm_s_axi_U_ap_dummy_ce;
wire   [31:0] grp_fu_45_p2;
reg    ap_sig_cseq_ST_st6_fsm_5;
reg    ap_sig_bdd_85;
wire    grp_fu_45_ce;
reg   [5:0] ap_NS_fsm;


targeted_function_rm_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_RM_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_RM_DATA_WIDTH ))
targeted_function_rm_s_axi_U(
    .AWVALID( s_axi_rm_AWVALID ),
    .AWREADY( s_axi_rm_AWREADY ),
    .AWADDR( s_axi_rm_AWADDR ),
    .WVALID( s_axi_rm_WVALID ),
    .WREADY( s_axi_rm_WREADY ),
    .WDATA( s_axi_rm_WDATA ),
    .WSTRB( s_axi_rm_WSTRB ),
    .ARVALID( s_axi_rm_ARVALID ),
    .ARREADY( s_axi_rm_ARREADY ),
    .ARADDR( s_axi_rm_ARADDR ),
    .RVALID( s_axi_rm_RVALID ),
    .RREADY( s_axi_rm_RREADY ),
    .RDATA( s_axi_rm_RDATA ),
    .RRESP( s_axi_rm_RRESP ),
    .BVALID( s_axi_rm_BVALID ),
    .BREADY( s_axi_rm_BREADY ),
    .BRESP( s_axi_rm_BRESP ),
    .ACLK( ap_clk ),
    .ARESET( ap_rst_n_inv ),
    .ACLK_EN( targeted_function_rm_s_axi_U_ap_dummy_ce ),
    .ap_start( ap_start ),
    .interrupt( interrupt ),
    .ap_ready( ap_ready ),
    .ap_done( ap_done ),
    .ap_idle( ap_idle ),
    .ap_return( ap_return ),
    .input_000( input_000 ),
    .input_001( input_001 ),
    .output_000( output_000 ),
    .output_000_ap_vld( output_000_ap_vld )
);

targeted_function_mul_32s_32s_32_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
targeted_function_mul_32s_32s_32_6_U0(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .din0( input_001 ),
    .din1( input_000 ),
    .ce( grp_fu_45_ce ),
    .dout( grp_fu_45_p2 )
);



always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (ap_sig_cseq_ST_st6_fsm_5) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st6_fsm_5) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_24) begin
    if (ap_sig_bdd_24) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_85) begin
    if (ap_sig_bdd_85) begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st6_fsm_5) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        output_000_ap_vld = ap_const_logic_1;
    end else begin
        output_000_ap_vld = ap_const_logic_0;
    end
end
always @ (ap_start or ap_CS_fsm) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            ap_NS_fsm = ap_ST_st3_fsm_2;
        end
        ap_ST_st3_fsm_2 : 
        begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        ap_ST_st4_fsm_3 : 
        begin
            ap_NS_fsm = ap_ST_st5_fsm_4;
        end
        ap_ST_st5_fsm_4 : 
        begin
            ap_NS_fsm = ap_ST_st6_fsm_5;
        end
        ap_ST_st6_fsm_5 : 
        begin
            ap_NS_fsm = ap_ST_st1_fsm_0;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end


assign ap_return = ap_const_lv32_0;


always @ (ap_rst_n) begin
    ap_rst_n_inv = ~ap_rst_n;
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_24 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_85 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_5]);
end

assign grp_fu_45_ce = ap_const_logic_1;

assign output_000 = grp_fu_45_p2;

assign targeted_function_rm_s_axi_U_ap_dummy_ce = ap_const_logic_1;


endmodule //targeted_function

