// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "targeted_function.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic targeted_function::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic targeted_function::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> targeted_function::ap_ST_st1_fsm_0 = "1";
const sc_lv<2> targeted_function::ap_ST_st2_fsm_1 = "10";
const sc_lv<32> targeted_function::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> targeted_function::ap_const_lv1_1 = "1";
const int targeted_function::C_S_AXI_DATA_WIDTH = "100000";
const sc_lv<1> targeted_function::ap_const_lv1_0 = "0";
const sc_lv<32> targeted_function::ap_const_lv32_1 = "1";
const sc_lv<6> targeted_function::ap_const_lv6_1 = "1";
const sc_lv<32> targeted_function::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_lv<32> targeted_function::ap_const_lv32_1F = "11111";
const sc_lv<32> targeted_function::ap_const_lv32_2E = "101110";
const sc_lv<31> targeted_function::ap_const_lv31_1 = "1";

targeted_function::targeted_function(sc_module_name name) : sc_module(name), mVcdFile(0) {
    targeted_function_rm_s_axi_U = new targeted_function_rm_s_axi<C_S_AXI_RM_ADDR_WIDTH,C_S_AXI_RM_DATA_WIDTH>("targeted_function_rm_s_axi_U");
    targeted_function_rm_s_axi_U->AWVALID(s_axi_rm_AWVALID);
    targeted_function_rm_s_axi_U->AWREADY(s_axi_rm_AWREADY);
    targeted_function_rm_s_axi_U->AWADDR(s_axi_rm_AWADDR);
    targeted_function_rm_s_axi_U->WVALID(s_axi_rm_WVALID);
    targeted_function_rm_s_axi_U->WREADY(s_axi_rm_WREADY);
    targeted_function_rm_s_axi_U->WDATA(s_axi_rm_WDATA);
    targeted_function_rm_s_axi_U->WSTRB(s_axi_rm_WSTRB);
    targeted_function_rm_s_axi_U->ARVALID(s_axi_rm_ARVALID);
    targeted_function_rm_s_axi_U->ARREADY(s_axi_rm_ARREADY);
    targeted_function_rm_s_axi_U->ARADDR(s_axi_rm_ARADDR);
    targeted_function_rm_s_axi_U->RVALID(s_axi_rm_RVALID);
    targeted_function_rm_s_axi_U->RREADY(s_axi_rm_RREADY);
    targeted_function_rm_s_axi_U->RDATA(s_axi_rm_RDATA);
    targeted_function_rm_s_axi_U->RRESP(s_axi_rm_RRESP);
    targeted_function_rm_s_axi_U->BVALID(s_axi_rm_BVALID);
    targeted_function_rm_s_axi_U->BREADY(s_axi_rm_BREADY);
    targeted_function_rm_s_axi_U->BRESP(s_axi_rm_BRESP);
    targeted_function_rm_s_axi_U->ACLK(ap_clk);
    targeted_function_rm_s_axi_U->ARESET(ap_rst_n_inv);
    targeted_function_rm_s_axi_U->ACLK_EN(targeted_function_rm_s_axi_U_ap_dummy_ce);
    targeted_function_rm_s_axi_U->ap_start(ap_start);
    targeted_function_rm_s_axi_U->interrupt(interrupt);
    targeted_function_rm_s_axi_U->ap_ready(ap_ready);
    targeted_function_rm_s_axi_U->ap_done(ap_done);
    targeted_function_rm_s_axi_U->ap_idle(ap_idle);
    targeted_function_rm_s_axi_U->ap_return(ap_return);
    targeted_function_rm_s_axi_U->input_000(input_000);
    targeted_function_rm_s_axi_U->output_000(output_000);
    targeted_function_rm_s_axi_U->output_000_ap_vld(output_000_ap_vld);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( or_cond_reg_189 );
    sensitive << ( icmp_reg_193 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond_fu_158_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( or_cond_reg_189 );
    sensitive << ( icmp_reg_193 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond_fu_158_p2 );

    SC_METHOD(thread_ap_return);
    sensitive << ( or_cond_reg_189 );
    sensitive << ( icmp_reg_193 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond_fu_158_p2 );
    sensitive << ( p_0_phi_fu_107_p6 );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sig_bdd_20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_86);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_20 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_86 );

    SC_METHOD(thread_exitcond_fu_158_p2);
    sensitive << ( input_000_read_reg_184 );
    sensitive << ( or_cond_reg_189 );
    sensitive << ( icmp_reg_193 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( i_cast_fu_154_p1 );

    SC_METHOD(thread_i_1_fu_170_p2);
    sensitive << ( i_reg_67 );

    SC_METHOD(thread_i_cast_fu_154_p1);
    sensitive << ( i_reg_67 );

    SC_METHOD(thread_icmp_fu_148_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( or_cond_fu_132_p2 );
    sensitive << ( tmp_2_fu_138_p4 );

    SC_METHOD(thread_or_cond_fu_132_p2);
    sensitive << ( tmp_fu_118_p3 );
    sensitive << ( tmp_1_fu_126_p2 );

    SC_METHOD(thread_output_000);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( input_000 );
    sensitive << ( or_cond_fu_132_p2 );
    sensitive << ( or_cond_reg_189 );
    sensitive << ( icmp_fu_148_p2 );
    sensitive << ( icmp_reg_193 );
    sensitive << ( second_fu_163_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond_fu_158_p2 );

    SC_METHOD(thread_output_000_ap_vld);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( or_cond_fu_132_p2 );
    sensitive << ( or_cond_reg_189 );
    sensitive << ( icmp_fu_148_p2 );
    sensitive << ( icmp_reg_193 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond_fu_158_p2 );

    SC_METHOD(thread_p_0_phi_fu_107_p6);
    sensitive << ( or_cond_reg_189 );
    sensitive << ( icmp_reg_193 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond_fu_158_p2 );
    sensitive << ( p_0_reg_102 );

    SC_METHOD(thread_second_fu_163_p2);
    sensitive << ( first_reg_78 );
    sensitive << ( first_1_reg_89 );

    SC_METHOD(thread_targeted_function_rm_s_axi_U_ap_dummy_ce);

    SC_METHOD(thread_tmp_1_fu_126_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( input_000 );

    SC_METHOD(thread_tmp_2_fu_138_p4);
    sensitive << ( input_000 );

    SC_METHOD(thread_tmp_fu_118_p3);
    sensitive << ( input_000 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( or_cond_reg_189 );
    sensitive << ( icmp_reg_193 );
    sensitive << ( exitcond_fu_158_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "01";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "targeted_function_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, s_axi_rm_AWVALID, "(port)s_axi_rm_AWVALID");
    sc_trace(mVcdFile, s_axi_rm_AWREADY, "(port)s_axi_rm_AWREADY");
    sc_trace(mVcdFile, s_axi_rm_AWADDR, "(port)s_axi_rm_AWADDR");
    sc_trace(mVcdFile, s_axi_rm_WVALID, "(port)s_axi_rm_WVALID");
    sc_trace(mVcdFile, s_axi_rm_WREADY, "(port)s_axi_rm_WREADY");
    sc_trace(mVcdFile, s_axi_rm_WDATA, "(port)s_axi_rm_WDATA");
    sc_trace(mVcdFile, s_axi_rm_WSTRB, "(port)s_axi_rm_WSTRB");
    sc_trace(mVcdFile, s_axi_rm_ARVALID, "(port)s_axi_rm_ARVALID");
    sc_trace(mVcdFile, s_axi_rm_ARREADY, "(port)s_axi_rm_ARREADY");
    sc_trace(mVcdFile, s_axi_rm_ARADDR, "(port)s_axi_rm_ARADDR");
    sc_trace(mVcdFile, s_axi_rm_RVALID, "(port)s_axi_rm_RVALID");
    sc_trace(mVcdFile, s_axi_rm_RREADY, "(port)s_axi_rm_RREADY");
    sc_trace(mVcdFile, s_axi_rm_RDATA, "(port)s_axi_rm_RDATA");
    sc_trace(mVcdFile, s_axi_rm_RRESP, "(port)s_axi_rm_RRESP");
    sc_trace(mVcdFile, s_axi_rm_BVALID, "(port)s_axi_rm_BVALID");
    sc_trace(mVcdFile, s_axi_rm_BREADY, "(port)s_axi_rm_BREADY");
    sc_trace(mVcdFile, s_axi_rm_BRESP, "(port)s_axi_rm_BRESP");
    sc_trace(mVcdFile, interrupt, "(port)interrupt");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ap_start, "ap_start");
    sc_trace(mVcdFile, ap_done, "ap_done");
    sc_trace(mVcdFile, ap_idle, "ap_idle");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_20, "ap_sig_bdd_20");
    sc_trace(mVcdFile, ap_ready, "ap_ready");
    sc_trace(mVcdFile, input_000, "input_000");
    sc_trace(mVcdFile, output_000, "output_000");
    sc_trace(mVcdFile, output_000_ap_vld, "output_000_ap_vld");
    sc_trace(mVcdFile, ap_return, "ap_return");
    sc_trace(mVcdFile, targeted_function_rm_s_axi_U_ap_dummy_ce, "targeted_function_rm_s_axi_U_ap_dummy_ce");
    sc_trace(mVcdFile, input_000_read_reg_184, "input_000_read_reg_184");
    sc_trace(mVcdFile, or_cond_fu_132_p2, "or_cond_fu_132_p2");
    sc_trace(mVcdFile, or_cond_reg_189, "or_cond_reg_189");
    sc_trace(mVcdFile, icmp_fu_148_p2, "icmp_fu_148_p2");
    sc_trace(mVcdFile, icmp_reg_193, "icmp_reg_193");
    sc_trace(mVcdFile, second_fu_163_p2, "second_fu_163_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_86, "ap_sig_bdd_86");
    sc_trace(mVcdFile, exitcond_fu_158_p2, "exitcond_fu_158_p2");
    sc_trace(mVcdFile, i_1_fu_170_p2, "i_1_fu_170_p2");
    sc_trace(mVcdFile, i_reg_67, "i_reg_67");
    sc_trace(mVcdFile, first_reg_78, "first_reg_78");
    sc_trace(mVcdFile, first_1_reg_89, "first_1_reg_89");
    sc_trace(mVcdFile, p_0_phi_fu_107_p6, "p_0_phi_fu_107_p6");
    sc_trace(mVcdFile, p_0_reg_102, "p_0_reg_102");
    sc_trace(mVcdFile, tmp_fu_118_p3, "tmp_fu_118_p3");
    sc_trace(mVcdFile, tmp_1_fu_126_p2, "tmp_1_fu_126_p2");
    sc_trace(mVcdFile, tmp_2_fu_138_p4, "tmp_2_fu_138_p4");
    sc_trace(mVcdFile, i_cast_fu_154_p1, "i_cast_fu_154_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("targeted_function.hdltvin.dat");
    mHdltvoutHandle.open("targeted_function.hdltvout.dat");
}

targeted_function::~targeted_function() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete targeted_function_rm_s_axi_U;
}

void targeted_function::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(or_cond_fu_132_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(icmp_fu_148_p2.read(), ap_const_lv1_0))) {
        first_1_reg_89 = ap_const_lv32_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                esl_seteq<1,1,1>(or_cond_reg_189.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(icmp_reg_193.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_158_p2.read()))) {
        first_1_reg_89 = second_fu_163_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(or_cond_fu_132_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(icmp_fu_148_p2.read(), ap_const_lv1_0))) {
        first_reg_78 = ap_const_lv32_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                esl_seteq<1,1,1>(or_cond_reg_189.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(icmp_reg_193.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_158_p2.read()))) {
        first_reg_78 = first_1_reg_89.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(or_cond_fu_132_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(icmp_fu_148_p2.read(), ap_const_lv1_0))) {
        i_reg_67 = ap_const_lv6_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                esl_seteq<1,1,1>(or_cond_reg_189.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(icmp_reg_193.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_158_p2.read()))) {
        i_reg_67 = i_1_fu_170_p2.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
          esl_seteq<1,1,1>(or_cond_fu_132_p2.read(), ap_const_lv1_0) && 
          !esl_seteq<1,1,1>(icmp_fu_148_p2.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          esl_seteq<1,1,1>(or_cond_reg_189.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(icmp_reg_193.read(), ap_const_lv1_0) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_158_p2.read())))) {
        p_0_reg_102 = ap_const_lv1_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
                !esl_seteq<1,1,1>(or_cond_fu_132_p2.read(), ap_const_lv1_0))) {
        p_0_reg_102 = ap_const_lv1_1;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && esl_seteq<1,1,1>(or_cond_fu_132_p2.read(), ap_const_lv1_0))) {
        icmp_reg_193 = icmp_fu_148_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        input_000_read_reg_184 = input_000.read();
        or_cond_reg_189 = or_cond_fu_132_p2.read();
    }
}

void targeted_function::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_158_p2.read()) || 
          !esl_seteq<1,1,1>(or_cond_reg_189.read(), ap_const_lv1_0) || 
          !esl_seteq<1,1,1>(icmp_reg_193.read(), ap_const_lv1_0)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void targeted_function::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void targeted_function::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_158_p2.read()) || 
          !esl_seteq<1,1,1>(or_cond_reg_189.read(), ap_const_lv1_0) || 
          !esl_seteq<1,1,1>(icmp_reg_193.read(), ap_const_lv1_0)))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void targeted_function::thread_ap_return() {
    ap_return = (!p_0_phi_fu_107_p6.read()[0].is_01())? sc_lv<32>(): ((p_0_phi_fu_107_p6.read()[0].to_bool())? ap_const_lv32_FFFFFFFF: ap_const_lv32_0);
}

void targeted_function::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void targeted_function::thread_ap_sig_bdd_20() {
    ap_sig_bdd_20 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void targeted_function::thread_ap_sig_bdd_86() {
    ap_sig_bdd_86 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void targeted_function::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_20.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void targeted_function::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_86.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void targeted_function::thread_exitcond_fu_158_p2() {
    exitcond_fu_158_p2 = (!i_cast_fu_154_p1.read().is_01() || !input_000_read_reg_184.read().is_01())? sc_lv<1>(): sc_lv<1>(i_cast_fu_154_p1.read() == input_000_read_reg_184.read());
}

void targeted_function::thread_i_1_fu_170_p2() {
    i_1_fu_170_p2 = (!i_reg_67.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(i_reg_67.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void targeted_function::thread_i_cast_fu_154_p1() {
    i_cast_fu_154_p1 = esl_zext<32,6>(i_reg_67.read());
}

void targeted_function::thread_icmp_fu_148_p2() {
    icmp_fu_148_p2 = (!tmp_2_fu_138_p4.read().is_01() || !ap_const_lv31_1.is_01())? sc_lv<1>(): (sc_bigint<31>(tmp_2_fu_138_p4.read()) < sc_bigint<31>(ap_const_lv31_1));
}

void targeted_function::thread_or_cond_fu_132_p2() {
    or_cond_fu_132_p2 = (tmp_fu_118_p3.read() | tmp_1_fu_126_p2.read());
}

void targeted_function::thread_output_000() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(or_cond_reg_189.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(icmp_reg_193.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_158_p2.read()))) {
        output_000 = second_fu_163_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
                !esl_seteq<1,1,1>(or_cond_fu_132_p2.read(), ap_const_lv1_0))) {
        output_000 = ap_const_lv32_FFFFFFFF;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
                esl_seteq<1,1,1>(or_cond_fu_132_p2.read(), ap_const_lv1_0) && 
                !esl_seteq<1,1,1>(icmp_fu_148_p2.read(), ap_const_lv1_0))) {
        output_000 = input_000.read();
    } else {
        output_000 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void targeted_function::thread_output_000_ap_vld() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          esl_seteq<1,1,1>(or_cond_reg_189.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(icmp_reg_193.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_158_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
          !esl_seteq<1,1,1>(or_cond_fu_132_p2.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
          esl_seteq<1,1,1>(or_cond_fu_132_p2.read(), ap_const_lv1_0) && 
          !esl_seteq<1,1,1>(icmp_fu_148_p2.read(), ap_const_lv1_0)))) {
        output_000_ap_vld = ap_const_logic_1;
    } else {
        output_000_ap_vld = ap_const_logic_0;
    }
}

void targeted_function::thread_p_0_phi_fu_107_p6() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(or_cond_reg_189.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(icmp_reg_193.read(), ap_const_lv1_0) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_158_p2.read()))) {
        p_0_phi_fu_107_p6 = ap_const_lv1_0;
    } else {
        p_0_phi_fu_107_p6 = p_0_reg_102.read();
    }
}

void targeted_function::thread_second_fu_163_p2() {
    second_fu_163_p2 = (!first_reg_78.read().is_01() || !first_1_reg_89.read().is_01())? sc_lv<32>(): (sc_biguint<32>(first_reg_78.read()) + sc_biguint<32>(first_1_reg_89.read()));
}

void targeted_function::thread_targeted_function_rm_s_axi_U_ap_dummy_ce() {
    targeted_function_rm_s_axi_U_ap_dummy_ce = ap_const_logic_1;
}

void targeted_function::thread_tmp_1_fu_126_p2() {
    tmp_1_fu_126_p2 = (!input_000.read().is_01() || !ap_const_lv32_2E.is_01())? sc_lv<1>(): (sc_bigint<32>(input_000.read()) > sc_bigint<32>(ap_const_lv32_2E));
}

void targeted_function::thread_tmp_2_fu_138_p4() {
    tmp_2_fu_138_p4 = input_000.read().range(31, 1);
}

void targeted_function::thread_tmp_fu_118_p3() {
    tmp_fu_118_p3 = input_000.read().range(31, 31);
}

void targeted_function::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if ((!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_158_p2.read()) || !esl_seteq<1,1,1>(or_cond_reg_189.read(), ap_const_lv1_0) || !esl_seteq<1,1,1>(icmp_reg_193.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<2>) ("XX");
            break;
    }
}

void targeted_function::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_rm_AWVALID\" :  \"" << s_axi_rm_AWVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"s_axi_rm_AWREADY\" :  \"" << s_axi_rm_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_rm_AWADDR\" :  \"" << s_axi_rm_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_rm_WVALID\" :  \"" << s_axi_rm_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_rm_WREADY\" :  \"" << s_axi_rm_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_rm_WDATA\" :  \"" << s_axi_rm_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_rm_WSTRB\" :  \"" << s_axi_rm_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_rm_ARVALID\" :  \"" << s_axi_rm_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_rm_ARREADY\" :  \"" << s_axi_rm_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_rm_ARADDR\" :  \"" << s_axi_rm_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_rm_RVALID\" :  \"" << s_axi_rm_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_rm_RREADY\" :  \"" << s_axi_rm_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_rm_RDATA\" :  \"" << s_axi_rm_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_rm_RRESP\" :  \"" << s_axi_rm_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_rm_BVALID\" :  \"" << s_axi_rm_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_rm_BREADY\" :  \"" << s_axi_rm_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_rm_BRESP\" :  \"" << s_axi_rm_BRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"interrupt\" :  \"" << interrupt.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

