// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _targeted_function_HH_
#define _targeted_function_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "targeted_function_srem_32ns_32ns_32_36_seq.h"
#include "targeted_function_rm_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_RM_ADDR_WIDTH = 6,
         unsigned int C_S_AXI_RM_DATA_WIDTH = 32>
struct targeted_function : public sc_module {
    // Port declarations 20
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_logic > s_axi_rm_AWVALID;
    sc_out< sc_logic > s_axi_rm_AWREADY;
    sc_in< sc_uint<C_S_AXI_RM_ADDR_WIDTH> > s_axi_rm_AWADDR;
    sc_in< sc_logic > s_axi_rm_WVALID;
    sc_out< sc_logic > s_axi_rm_WREADY;
    sc_in< sc_uint<C_S_AXI_RM_DATA_WIDTH> > s_axi_rm_WDATA;
    sc_in< sc_uint<C_S_AXI_RM_DATA_WIDTH/8> > s_axi_rm_WSTRB;
    sc_in< sc_logic > s_axi_rm_ARVALID;
    sc_out< sc_logic > s_axi_rm_ARREADY;
    sc_in< sc_uint<C_S_AXI_RM_ADDR_WIDTH> > s_axi_rm_ARADDR;
    sc_out< sc_logic > s_axi_rm_RVALID;
    sc_in< sc_logic > s_axi_rm_RREADY;
    sc_out< sc_uint<C_S_AXI_RM_DATA_WIDTH> > s_axi_rm_RDATA;
    sc_out< sc_lv<2> > s_axi_rm_RRESP;
    sc_out< sc_logic > s_axi_rm_BVALID;
    sc_in< sc_logic > s_axi_rm_BREADY;
    sc_out< sc_lv<2> > s_axi_rm_BRESP;
    sc_out< sc_logic > interrupt;


    // Module declarations
    targeted_function(sc_module_name name);
    SC_HAS_PROCESS(targeted_function);

    ~targeted_function();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    targeted_function_rm_s_axi<C_S_AXI_RM_ADDR_WIDTH,C_S_AXI_RM_DATA_WIDTH>* targeted_function_rm_s_axi_U;
    targeted_function_srem_32ns_32ns_32_36_seq<1,36,32,32,32>* targeted_function_srem_32ns_32ns_32_36_seq_U0;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > ap_start;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_lv<5> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_bdd_23;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_lv<32> > input_000;
    sc_signal< sc_lv<32> > output_000;
    sc_signal< sc_logic > output_000_ap_vld;
    sc_signal< sc_lv<32> > ap_return;
    sc_signal< sc_logic > targeted_function_rm_s_axi_U_ap_dummy_ce;
    sc_signal< sc_lv<32> > input_000_read_reg_185;
    sc_signal< sc_lv<32> > i_load_reg_200;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_bdd_82;
    sc_signal< sc_lv<32> > tmp_3_fu_126_p2;
    sc_signal< sc_lv<32> > tmp_3_reg_208;
    sc_signal< sc_lv<1> > tmp_2_fu_121_p2;
    sc_signal< sc_lv<1> > tmp_4_fu_132_p2;
    sc_signal< sc_lv<1> > tmp_4_reg_213;
    sc_signal< sc_logic > ap_sig_cseq_ST_st3_fsm_2;
    sc_signal< bool > ap_sig_bdd_97;
    sc_signal< sc_lv<32> > j_1_fu_149_p2;
    sc_signal< sc_logic > ap_sig_cseq_ST_st4_fsm_3;
    sc_signal< bool > ap_sig_bdd_106;
    sc_signal< sc_logic > grp_fu_137_ap_done;
    sc_signal< sc_lv<1> > tmp_6_fu_143_p2;
    sc_signal< sc_lv<32> > ctr_1_fu_171_p2;
    sc_signal< sc_lv<32> > ctr_reg_57;
    sc_signal< sc_lv<1> > or_cond_fu_107_p2;
    sc_signal< sc_lv<32> > j_reg_70;
    sc_signal< sc_lv<1> > p_0_reg_82;
    sc_signal< sc_lv<32> > i_fu_38;
    sc_signal< sc_lv<32> > i_1_fu_161_p2;
    sc_signal< sc_lv<1> > tmp_7_fu_155_p2;
    sc_signal< sc_lv<1> > tmp_fu_95_p2;
    sc_signal< sc_lv<1> > tmp_1_fu_101_p2;
    sc_signal< sc_lv<32> > grp_fu_137_p2;
    sc_signal< sc_logic > ap_sig_cseq_ST_st5_fsm_4;
    sc_signal< bool > ap_sig_bdd_187;
    sc_signal< sc_logic > grp_fu_137_ap_start;
    sc_signal< sc_logic > grp_fu_137_ce;
    sc_signal< sc_lv<5> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<5> ap_ST_st1_fsm_0;
    static const sc_lv<5> ap_ST_st2_fsm_1;
    static const sc_lv<5> ap_ST_st3_fsm_2;
    static const sc_lv<5> ap_ST_st4_fsm_3;
    static const sc_lv<5> ap_ST_st5_fsm_4;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const int C_S_AXI_DATA_WIDTH;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_FFFFFFFF;
    static const sc_lv<32> ap_const_lv32_643A95D;
    static const sc_lv<32> ap_const_lv32_4;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_ap_rst_n_inv();
    void thread_ap_sig_bdd_106();
    void thread_ap_sig_bdd_187();
    void thread_ap_sig_bdd_23();
    void thread_ap_sig_bdd_82();
    void thread_ap_sig_bdd_97();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_ap_sig_cseq_ST_st3_fsm_2();
    void thread_ap_sig_cseq_ST_st4_fsm_3();
    void thread_ap_sig_cseq_ST_st5_fsm_4();
    void thread_ctr_1_fu_171_p2();
    void thread_grp_fu_137_ap_start();
    void thread_grp_fu_137_ce();
    void thread_i_1_fu_161_p2();
    void thread_j_1_fu_149_p2();
    void thread_or_cond_fu_107_p2();
    void thread_output_000();
    void thread_output_000_ap_vld();
    void thread_targeted_function_rm_s_axi_U_ap_dummy_ce();
    void thread_tmp_1_fu_101_p2();
    void thread_tmp_2_fu_121_p2();
    void thread_tmp_3_fu_126_p2();
    void thread_tmp_4_fu_132_p2();
    void thread_tmp_6_fu_143_p2();
    void thread_tmp_7_fu_155_p2();
    void thread_tmp_fu_95_p2();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
