// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XTARGETED_FUNCTION_H
#define XTARGETED_FUNCTION_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xtargeted_function_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Rm_BaseAddress;
} XTargeted_function_Config;
#endif

typedef struct {
    u32 Rm_BaseAddress;
    u32 IsReady;
} XTargeted_function;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XTargeted_function_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XTargeted_function_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XTargeted_function_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XTargeted_function_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XTargeted_function_Initialize(XTargeted_function *InstancePtr, u16 DeviceId);
XTargeted_function_Config* XTargeted_function_LookupConfig(u16 DeviceId);
int XTargeted_function_CfgInitialize(XTargeted_function *InstancePtr, XTargeted_function_Config *ConfigPtr);
#else
int XTargeted_function_Initialize(XTargeted_function *InstancePtr, const char* InstanceName);
int XTargeted_function_Release(XTargeted_function *InstancePtr);
#endif

void XTargeted_function_Start(XTargeted_function *InstancePtr);
u32 XTargeted_function_IsDone(XTargeted_function *InstancePtr);
u32 XTargeted_function_IsIdle(XTargeted_function *InstancePtr);
u32 XTargeted_function_IsReady(XTargeted_function *InstancePtr);
void XTargeted_function_EnableAutoRestart(XTargeted_function *InstancePtr);
void XTargeted_function_DisableAutoRestart(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_return(XTargeted_function *InstancePtr);

u32 XTargeted_function_Get_output_000(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_000_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_001(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_001_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_002(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_002_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_003(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_003_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_004(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_004_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_005(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_005_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_006(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_006_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_007(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_007_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_008(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_008_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_009(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_009_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_010(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_010_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_011(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_011_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_012(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_012_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_013(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_013_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_014(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_014_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_015(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_015_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_016(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_016_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_017(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_017_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_018(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_018_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_019(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_019_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_020(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_020_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_021(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_021_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_022(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_022_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_023(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_023_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_024(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_024_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_025(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_025_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_026(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_026_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_027(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_027_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_028(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_028_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_029(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_029_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_030(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_030_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_031(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_031_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_032(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_032_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_033(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_033_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_034(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_034_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_035(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_035_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_036(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_036_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_037(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_037_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_038(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_038_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_039(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_039_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_040(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_040_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_041(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_041_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_042(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_042_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_043(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_043_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_044(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_044_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_045(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_045_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_046(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_046_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_047(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_047_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_048(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_048_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_049(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_049_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_050(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_050_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_051(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_051_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_052(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_052_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_053(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_053_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_054(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_054_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_055(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_055_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_056(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_056_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_057(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_057_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_058(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_058_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_059(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_059_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_060(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_060_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_061(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_061_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_062(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_062_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_063(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_063_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_064(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_064_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_065(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_065_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_066(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_066_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_067(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_067_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_068(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_068_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_069(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_069_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_070(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_070_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_071(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_071_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_072(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_072_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_073(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_073_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_074(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_074_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_075(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_075_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_076(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_076_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_077(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_077_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_078(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_078_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_079(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_079_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_080(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_080_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_081(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_081_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_082(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_082_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_083(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_083_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_084(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_084_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_085(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_085_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_086(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_086_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_087(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_087_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_088(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_088_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_089(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_089_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_090(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_090_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_091(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_091_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_092(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_092_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_093(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_093_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_094(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_094_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_095(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_095_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_096(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_096_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_097(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_097_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_098(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_098_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_099(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_099_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_100(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_100_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_101(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_101_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_102(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_102_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_103(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_103_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_104(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_104_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_105(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_105_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_106(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_106_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_107(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_107_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_108(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_108_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_109(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_109_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_110(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_110_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_111(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_111_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_112(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_112_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_113(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_113_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_114(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_114_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_115(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_115_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_116(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_116_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_117(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_117_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_118(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_118_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_119(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_119_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_120(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_120_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_121(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_121_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_122(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_122_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_123(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_123_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_124(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_124_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_125(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_125_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_126(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_126_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_127(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_127_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_128(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_128_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_129(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_129_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_130(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_130_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_131(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_131_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_132(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_132_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_133(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_133_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_134(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_134_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_135(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_135_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_136(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_136_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_137(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_137_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_138(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_138_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_139(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_139_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_140(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_140_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_141(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_141_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_142(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_142_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_143(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_143_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_144(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_144_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_145(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_145_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_146(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_146_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_147(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_147_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_148(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_148_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_149(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_149_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_150(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_150_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_151(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_151_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_152(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_152_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_153(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_153_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_154(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_154_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_155(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_155_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_156(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_156_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_157(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_157_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_158(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_158_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_159(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_159_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_160(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_160_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_161(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_161_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_162(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_162_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_163(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_163_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_164(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_164_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_165(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_165_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_166(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_166_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_167(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_167_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_168(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_168_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_169(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_169_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_170(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_170_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_171(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_171_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_172(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_172_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_173(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_173_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_174(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_174_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_175(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_175_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_176(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_176_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_177(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_177_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_178(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_178_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_179(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_179_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_180(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_180_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_181(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_181_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_182(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_182_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_183(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_183_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_184(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_184_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_185(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_185_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_186(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_186_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_187(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_187_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_188(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_188_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_189(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_189_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_190(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_190_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_191(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_191_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_192(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_192_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_193(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_193_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_194(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_194_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_195(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_195_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_196(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_196_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_197(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_197_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_198(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_198_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_199(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_199_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_200(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_200_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_201(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_201_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_202(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_202_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_203(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_203_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_204(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_204_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_205(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_205_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_206(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_206_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_207(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_207_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_208(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_208_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_209(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_209_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_210(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_210_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_211(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_211_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_212(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_212_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_213(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_213_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_214(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_214_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_215(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_215_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_216(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_216_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_217(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_217_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_218(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_218_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_219(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_219_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_220(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_220_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_221(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_221_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_222(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_222_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_223(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_223_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_224(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_224_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_225(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_225_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_226(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_226_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_227(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_227_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_228(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_228_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_229(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_229_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_230(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_230_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_231(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_231_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_232(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_232_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_233(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_233_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_234(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_234_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_235(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_235_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_236(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_236_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_237(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_237_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_238(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_238_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_239(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_239_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_240(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_240_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_241(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_241_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_242(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_242_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_243(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_243_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_244(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_244_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_245(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_245_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_246(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_246_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_247(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_247_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_248(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_248_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_249(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_249_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_250(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_250_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_251(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_251_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_252(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_252_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_253(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_253_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_254(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_254_vld(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_255(XTargeted_function *InstancePtr);
u32 XTargeted_function_Get_output_255_vld(XTargeted_function *InstancePtr);

void XTargeted_function_InterruptGlobalEnable(XTargeted_function *InstancePtr);
void XTargeted_function_InterruptGlobalDisable(XTargeted_function *InstancePtr);
void XTargeted_function_InterruptEnable(XTargeted_function *InstancePtr, u32 Mask);
void XTargeted_function_InterruptDisable(XTargeted_function *InstancePtr, u32 Mask);
void XTargeted_function_InterruptClear(XTargeted_function *InstancePtr, u32 Mask);
u32 XTargeted_function_InterruptGetEnabled(XTargeted_function *InstancePtr);
u32 XTargeted_function_InterruptGetStatus(XTargeted_function *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
